version: "3"
services:
  mysql:
    image: mysql:5.7.23
    restart: always
    container_name: "mysql_5_7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybatis
    ports:
      - 3309:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
